/* ════════════════════════════════════════════════════════════════════
 * 电影清单 · 扩展片库 (~155 部) — 总片库达到 200+ 部
 * 全局变量：window.MOVIES_EXTRA
 * id 从 47 开始编号
 * ════════════════════════════════════════════════════════════════════ */
window.MOVIES_EXTRA = [
  // ─── 剧情 (id 47-66) ───
  {id:47,tmdbId:'tt0167260',title:'指环王：王者无敌',enTitle:'The Return of the King',year:2003,genre:'奇幻',poster:'',rating:9.3,director:'彼得·杰克逊',cast:'伊利亚·伍德, 维果·莫腾森',runtime:201,overview:'末日火山前的最后一战，护戒远征队面临最终的考验，中土世界的命运悬于一线。'},
  {id:48,tmdbId:'tt0167261',title:'指环王：双塔奇兵',enTitle:'The Two Towers',year:2002,genre:'奇幻',poster:'',rating:9.1,director:'彼得·杰克逊',cast:'伊利亚·伍德, 伊恩·麦克莱恩',runtime:179,overview:'护戒队解散后，阿拉贡带领洛汗国抵御萨鲁曼的进攻，弗罗多与山姆继续前往魔多。'},
  {id:49,tmdbId:'tt0073486',title:'飞越疯人院',enTitle:'One Flew Over the Cuckoo\'s Nest',year:1975,genre:'剧情',poster:'',rating:9.1,director:'米洛斯·福尔曼',cast:'杰克·尼科尔森, 路易丝·弗莱彻',runtime:133,overview:'为逃避劳教装疯入狱的麦克墨菲，用不羁点燃了疯人院里被驯服的灵魂。'},
  {id:50,tmdbId:'tt0114369',title:'七宗罪',enTitle:'Se7en',year:1995,genre:'悬疑',poster:'',rating:8.8,director:'大卫·芬奇',cast:'布拉德·皮特, 摩根·弗里曼',runtime:127,overview:'一名连环杀手按照七宗罪的教义实施谋杀，两名警探陷入了人性最黑暗的迷局。'},
  {id:51,tmdbId:'tt0080684',title:'星球大战：帝国反击战',enTitle:'The Empire Strikes Back',year:1980,genre:'科幻',poster:'',rating:8.7,director:'厄文·克什纳',cast:'马克·哈米尔, 哈里森·福特',runtime:124,overview:'帝国发动反击，卢克前往达戈巴寻找绝地大师尤达，而他与达斯·维达的宿命即将揭晓。'},
  {id:52,tmdbId:'tt0038650',title:'生活多美好',enTitle:'It\'s a Wonderful Life',year:1946,genre:'剧情',poster:'',rating:9.0,director:'弗兰克·卡普拉',cast:'詹姆斯·斯图尔特, 唐娜·里德',runtime:130,overview:'心灰意冷的乔治·贝利在天使的帮助下，看到了如果没有自己，这个世界会是怎样的光景。'},
  {id:53,tmdbId:'tt0099685',title:'好家伙',enTitle:'Goodfellas',year:1990,genre:'犯罪',poster:'',rating:8.7,director:'马丁·斯科塞斯',cast:'罗伯特·德尼罗, 雷·利奥塔',runtime:146,overview:'一个布鲁克林少年如何进入黑手党世界，享受权力与财富，最终又在背叛与危险中失去一切。'},
  {id:54,tmdbId:'tt0082971',title:'夺宝奇兵',enTitle:'Raiders of the Lost Ark',year:1981,genre:'动作',poster:'',rating:8.4,director:'史蒂文·斯皮尔伯格',cast:'哈里森·福特, 凯伦·阿兰',runtime:115,overview:'考古学家印第安纳·琼斯受命赶在纳粹之前找到传说中的约柜，环球冒险就此展开。'},
  {id:55,tmdbId:'tt0119217',title:'心灵捕手',enTitle:'Good Will Hunting',year:1997,genre:'剧情',poster:'',rating:8.6,director:'格斯·范·桑特',cast:'马特·达蒙, 罗宾·威廉姆斯',runtime:126,overview:'麻省理工学院清洁工威尔是个数学天才，在心理教授的引导下，慢慢打开尘封已久的心灵。'},
  {id:56,tmdbId:'tt0095327',title:'萤火虫之墓',enTitle:'Grave of the Fireflies',year:1988,genre:'动画',poster:'',rating:8.5,director:'高畑勋',cast:'辰巳努, 白石绫乃',runtime:89,overview:'二战末期，失去父母的兄妹在战火中艰难求生，用最脆弱的方式守护着彼此最后的希望。'},
  {id:57,tmdbId:'tt0034583',title:'卡萨布兰卡',enTitle:'Casablanca',year:1942,genre:'爱情',poster:'',rating:8.8,director:'迈克尔·柯蒂兹',cast:'亨弗莱·鲍嘉, 英格丽·褒曼',runtime:102,overview:'二战时期，夜总会老板里克在卡萨布兰卡重逢旧爱伊尔莎，必须在爱情与道义间做出抉择。'},
  {id:58,tmdbId:'tt0047478',title:'七武士',enTitle:'Seven Samurai',year:1954,genre:'动作',poster:'',rating:9.0,director:'黑泽明',cast:'三船敏郎, 志村乔',runtime:207,overview:'贫穷的村庄雇佣七名武士抵御山贼，一场史诗般的攻防战在泥土与血泪中展开。'},
  {id:59,tmdbId:'tt1853728',title:'被解救的姜戈',enTitle:'Django Unchained',year:2012,genre:'西部',poster:'',rating:8.5,director:'昆汀·塔伦蒂诺',cast:'杰米·福克斯, 莱昂纳多·迪卡普里奥',runtime:165,overview:'黑奴姜戈在德国赏金猎人的帮助下重获自由，踏上寻找妻子并复仇的血色之旅。'},
  {id:60,tmdbId:'tt0050083',title:'十二怒汉',enTitle:'12 Angry Men',year:1957,genre:'悬疑',poster:'',rating:9.4,director:'西德尼·吕美特',cast:'亨利·方达, 李·科布',runtime:96,overview:'陪审团密室里，一人坚持"合理怀疑"，层层拆解证据，守护司法的最后底线。'},
  {id:61,tmdbId:'tt0095765',title:'天堂电影院',enTitle:'Cinema Paradiso',year:1988,genre:'剧情',poster:'',rating:9.0,director:'朱塞佩·托纳多雷',cast:'菲利普·努瓦雷, 萨瓦特利·卡西欧',runtime:155,overview:'男孩多多与老放映师的忘年之交，在小镇电影院里经历了初恋、离别和成长的半生。'},
  {id:62,tmdbId:'tt1392190',title:'疯狂的麦克斯：狂暴之路',enTitle:'Mad Max: Fury Road',year:2015,genre:'动作',poster:'',rating:8.1,director:'乔治·米勒',cast:'汤姆·哈迪, 查理兹·塞隆',runtime:120,overview:'末日废土公路上的疯狂追逐，一位叛逃的女性将领与流浪者联手，在沙暴中杀出一条血路。'},
  {id:63,tmdbId:'tt0092005',title:'伴我同行',enTitle:'Stand by Me',year:1986,genre:'剧情',poster:'',rating:8.1,director:'罗伯·莱纳',cast:'威尔·惠顿, 瑞凡·菲尼克斯',runtime:89,overview:'四个男孩沿着铁轨寻找一具传说中的尸体，旅途中他们面对恐惧、友谊和成长的重量。'},
  {id:64,tmdbId:'tt0076759',title:'星球大战',enTitle:'Star Wars',year:1977,genre:'科幻',poster:'',rating:8.6,director:'乔治·卢卡斯',cast:'马克·哈米尔, 哈里森·福特',runtime:121,overview:'农场男孩卢克加入反抗军，与绝地武士欧比旺和走私贩汉·索罗一起，对抗银河帝国的压迫。'},
  {id:65,tmdbId:'tt0086190',title:'星球大战：绝地归来',enTitle:'Return of the Jedi',year:1983,genre:'科幻',poster:'',rating:8.3,director:'理查德·马昆德',cast:'马克·哈米尔, 哈里森·福特',runtime:131,overview:'卢克面对父亲达斯·维达，试图将被黑暗面吞噬的安纳金带回光明，帝国的命运即将终结。'},
  {id:66,tmdbId:'tt0075314',title:'出租车司机',enTitle:'Taxi Driver',year:1976,genre:'剧情',poster:'',rating:8.3,director:'马丁·斯科塞斯',cast:'罗伯特·德尼罗, 朱迪·福斯特',runtime:114,overview:'越战老兵特拉维斯在深夜纽约开出租车，目睹城市的腐化与罪恶，走上了自我毁灭的暴力之路。'},

  // ─── 犯罪/悬疑 (id 67-83) ───
  {id:67,tmdbId:'tt0060196',title:'黄金三镖客',enTitle:'The Good, the Bad and the Ugly',year:1966,genre:'西部',poster:'',rating:8.8,director:'赛尔乔·莱昂内',cast:'克林特·伊斯特伍德, 李·范·克里夫',runtime:178,overview:'三人各自追逐一笔被埋藏的黄金，在南北战争的硝烟中上演着背叛与对决的西部传奇。'},
  {id:68,tmdbId:'tt0209144',title:'记忆碎片',enTitle:'Memento',year:2000,genre:'悬疑',poster:'',rating:8.4,director:'克里斯托弗·诺兰',cast:'盖·皮尔斯, 凯瑞-安·莫斯',runtime:113,overview:'患有短期失忆症的莱纳德靠纹身和便签追查杀害妻子的凶手，时间错乱的叙述方式令人窒息。'},
  {id:69,tmdbId:'tt0078788',title:'现代启示录',enTitle:'Apocalypse Now',year:1979,genre:'战争',poster:'',rating:8.5,director:'弗朗西斯·科波拉',cast:'马丁·辛, 马龙·白兰度',runtime:147,overview:'越战中美军上尉奉命深入丛林处决叛变的库尔兹上校，沿途见证了战争的疯狂与荒谬。'},
  {id:70,tmdbId:'tt0054215',title:'惊魂记',enTitle:'Psycho',year:1960,genre:'悬疑',poster:'',rating:8.5,director:'阿尔弗雷德·希区柯克',cast:'安东尼·博金斯, 珍妮特·利',runtime:109,overview:'携款潜逃的玛丽安在偏僻汽车旅馆投宿，遇见了友善但异常的青年诺曼和他神秘的"母亲"。'},
  {id:71,tmdbId:'tt0071315',title:'唐人街',enTitle:'Chinatown',year:1974,genre:'悬疑',poster:'',rating:8.2,director:'罗曼·波兰斯基',cast:'杰克·尼科尔森, 费·唐纳薇',runtime:130,overview:'私家侦探杰克调查一桩通奸案，却被卷入洛杉矶水利系统的巨大阴谋，揭开层层黑幕。'},
  {id:72,tmdbId:'tt0372784',title:'蝙蝠侠：侠影之谜',enTitle:'Batman Begins',year:2005,genre:'动作',poster:'',rating:8.2,director:'克里斯托弗·诺兰',cast:'克里斯蒂安·贝尔, 迈克尔·凯恩',runtime:140,overview:'布鲁斯·韦恩游历世界学习武艺，回到哥谭市化身为蝙蝠侠，对抗城市深处的腐败与犯罪。'},
  {id:73,tmdbId:'tt0062622',title:'2001太空漫游',enTitle:'2001: A Space Odyssey',year:1968,genre:'科幻',poster:'',rating:8.3,director:'斯坦利·库布里克',cast:'凯尔·杜拉, 加里·洛克伍德',runtime:149,overview:'从史前黑石碑到太空深处的人工智能HAL 9000，人类探索宇宙的终极奥秘。'},
  {id:74,tmdbId:'tt0081398',title:'愤怒的公牛',enTitle:'Raging Bull',year:1980,genre:'剧情',poster:'',rating:8.2,director:'马丁·斯科塞斯',cast:'罗伯特·德尼罗, 乔·佩西',runtime:129,overview:'拳击冠军杰克·拉莫塔在拳台上所向披靡，在拳台下却被嫉妒、暴力与自我毁灭拖入深渊。'},
  {id:75,tmdbId:'tt0047296',title:'码头风云',enTitle:'On the Waterfront',year:1954,genre:'剧情',poster:'',rating:8.2,director:'伊利亚·卡赞',cast:'马龙·白兰度, 卡尔·马尔登',runtime:108,overview:'前拳击手特里在码头工会的黑帮控制下挣扎，最终站出来对抗不公，找回自己的尊严。'},
  {id:76,tmdbId:'tt0057012',title:'奇爱博士',enTitle:'Dr. Strangelove',year:1964,genre:'喜剧',poster:'',rating:8.4,director:'斯坦利·库布里克',cast:'彼得·塞勒斯, 乔治·斯科特',runtime:95,overview:'美军将领擅自发动核攻击，白宫作战室里军官们试图阻止这场即将毁灭人类的疯狂行动。'},
  {id:77,tmdbId:'tt0317248',title:'上帝之城',enTitle:'City of God',year:2002,genre:'犯罪',poster:'',rating:8.6,director:'费尔南多·梅里尔斯',cast:'亚历山大·罗德里格斯, 莱安德罗·菲尔米诺',runtime:130,overview:'里约热内卢贫民窟里的少年们在暴力、毒品和帮派战争中长大，有人选择拿起相机记录一切。'},
  {id:78,tmdbId:'tt0064115',title:'西部往事',enTitle:'Once Upon a Time in the West',year:1968,genre:'西部',poster:'',rating:8.5,director:'赛尔乔·莱昂内',cast:'亨利·方达, 查尔斯·布朗森',runtime:175,overview:'神秘口琴手来到大西部的铁路小镇，为了一段尘封的仇恨，也为了一个寡妇的未来。'},
  {id:79,tmdbId:'tt0082096',title:'从海底出击',enTitle:'Das Boot',year:1981,genre:'战争',poster:'',rating:8.4,director:'沃尔夫冈·彼得森',cast:'于尔根·普罗赫诺, 赫伯特·格勒内梅厄',runtime:149,overview:'二战中大西洋海底，德国U型潜艇船员在密闭、压抑、死亡恐惧中坚持执行任务。'},
  {id:80,tmdbId:'tt4154796',title:'复仇者联盟：终局之战',enTitle:'Avengers: Endgame',year:2019,genre:'动作',poster:'',rating:8.4,director:'安东尼·罗素',cast:'小罗伯特·唐尼, 克里斯·埃文斯',runtime:181,overview:'灭霸毁灭了宇宙一半生命，幸存的复仇者们穿越时空，赌上一切进行最后一战。'},
  {id:81,tmdbId:'tt4154756',title:'复仇者联盟：无限战争',enTitle:'Avengers: Infinity War',year:2018,genre:'动作',poster:'',rating:8.4,director:'安东尼·罗素',cast:'小罗伯特·唐尼, 乔什·布洛林',runtime:149,overview:'灭霸收集无限宝石的过程势不可挡，复仇者联盟和银河护卫队联手试图阻止他的疯狂计划。'},
  {id:82,tmdbId:'tt0088763',title:'回到未来',enTitle:'Back to the Future',year:1985,genre:'科幻',poster:'',rating:8.5,director:'罗伯特·泽米吉斯',cast:'迈克尔·J·福克斯, 克里斯托弗·洛伊德',runtime:116,overview:'高中生马蒂乘坐时光机回到了1955年，必须让年轻的父母恋爱才能回到未来。'},
  {id:83,tmdbId:'tt0112573',title:'勇敢的心',enTitle:'Braveheart',year:1995,genre:'战争',poster:'',rating:8.4,director:'梅尔·吉布森',cast:'梅尔·吉布森, 苏菲·玛索',runtime:178,overview:'苏格兰英雄威廉·华莱士带领人民反抗英格兰的暴政，为自由而战至最后一刻。'},

  // ─── 中国经典 (id 84-103) ───
  {id:84,tmdbId:'tt0170511',title:'活着',enTitle:'To Live',year:1994,genre:'剧情',poster:'',rating:9.3,director:'张艺谋',cast:'葛优, 巩俐',runtime:133,overview:'从民国到文革，福贵一家几代人的命运在中国大时代的变迁中飘摇，活着本身就是最大的勇气。'},
  {id:85,tmdbId:'tt0113249',title:'阳光灿烂的日子',enTitle:'In the Heat of the Sun',year:1994,genre:'剧情',poster:'',rating:8.9,director:'姜文',cast:'夏雨, 宁静',runtime:134,overview:'文革时期的北京大院里，少年们游手好闲度过了青春中最自由也最迷茫的那个夏天。'},
  {id:86,tmdbId:'tt0805519',title:'让子弹飞',enTitle:'Let the Bullets Fly',year:2010,genre:'喜剧',poster:'',rating:9.0,director:'姜文',cast:'姜文, 葛优, 周润发',runtime:132,overview:'民国乱世，劫匪冒充县长进驻鹅城，与地主恶霸展开一场酣畅淋漓的智斗与狂欢。'},
  {id:87,tmdbId:'tt0116857',title:'春光乍泄',enTitle:'Happy Together',year:1997,genre:'爱情',poster:'',rating:8.9,director:'王家卫',cast:'张国荣, 梁朝伟',runtime:96,overview:'一对同性恋人在阿根廷旅程中分分合合，相爱相杀的纠葛与孤独在南美的暮色中愈发深沉。'},
  {id:88,tmdbId:'tt0200720',title:'一一',enTitle:'Yi Yi',year:2000,genre:'剧情',poster:'',rating:8.9,director:'杨德昌',cast:'吴念真, 金燕玲',runtime:173,overview:'台北一个普通家庭三代人的日常，父亲、女儿和儿子各自面对人生不同阶段的困惑。'},
  {id:89,tmdbId:'tt0117006',title:'甜蜜蜜',enTitle:'Comrades: Almost a Love Story',year:1996,genre:'爱情',poster:'',rating:8.8,director:'陈可辛',cast:'黎明, 张曼玉',runtime:118,overview:'两个大陆来港青年在邓丽君的歌声里相遇相爱，移民时代的爱情与命运交织。'},
  {id:90,tmdbId:'tt0243353',title:'鬼子来了',enTitle:'Devils on the Doorstep',year:2000,genre:'战争',poster:'',rating:9.3,director:'姜文',cast:'姜文, 香川照之',runtime:139,overview:'抗战末期，河北农民马大三被迫收留一名日本俘虏和一名翻译，黑色荒诞与人性的拷问交织。'},
  {id:91,tmdbId:'tt0100374',title:'菊豆',enTitle:'Ju Dou',year:1990,genre:'剧情',poster:'',rating:8.2,director:'张艺谋',cast:'巩俐, 李保田',runtime:95,overview:'染坊少妇菊豆与长工天青暗生情愫，在封建礼教的重压下走向无法挽回的悲剧。'},
  {id:92,tmdbId:'tt0085080',title:'黄土地',enTitle:'Yellow Earth',year:1984,genre:'剧情',poster:'',rating:8.3,director:'陈凯歌',cast:'王学圻, 薛白',runtime:89,overview:'八路军文艺兵来到陕北黄土地上收集民歌，用镜头定格了这片土地上沉默千年的苦难与坚韧。'},
  {id:93,tmdbId:'tt1492652',title:'一代宗师',enTitle:'The Grandmaster',year:2013,genre:'动作',poster:'',rating:8.3,director:'王家卫',cast:'梁朝伟, 章子怡',runtime:130,overview:'咏春拳宗师叶问的传奇一生，从佛山到香港，以拳代言说了一段时代洪流中的武林往事。'},
  {id:94,tmdbId:'tt0362284',title:'疯狂的石头',enTitle:'Crazy Stone',year:2006,genre:'喜剧',poster:'',rating:8.5,director:'宁浩',cast:'郭涛, 黄渤',runtime:98,overview:'一块价值连城的翡翠引来了各路人马，在重庆山城上演了一出荒诞离奇的多线黑色喜剧。'},
  {id:95,tmdbId:'tt0295467',title:'英雄',enTitle:'Hero',year:2002,genre:'动作',poster:'',rating:8.1,director:'张艺谋',cast:'李连杰, 梁朝伟, 张曼玉',runtime:99,overview:'无名刺客向秦王讲述他如何击败三名刺客的故事，每一段讲述在色彩与武学中层层反转。'},
  {id:96,tmdbId:'tt0218658',title:'卧虎藏龙',enTitle:'Crouching Tiger, Hidden Dragon',year:2000,genre:'动作',poster:'',rating:8.3,director:'李安',cast:'周润发, 杨紫琼, 章子怡',runtime:120,overview:'一代大侠将青冥剑交出归隐，却被神秘盗贼偷走，一场竹林飞檐走壁的江湖恩仇就此铺开。'},
  {id:97,tmdbId:'tt0488188',title:'可可西里',enTitle:'Mountain Patrol',year:2004,genre:'剧情',poster:'',rating:8.8,director:'陆川',cast:'多布杰, 张磊',runtime:90,overview:'志愿巡山队与盗猎者在荒凉的可可西里无人区展开残酷对抗，守护藏羚羊的最后栖息地。'},
  {id:98,tmdbId:'tt0154420',title:'喜剧之王',enTitle:'King of Comedy',year:1999,genre:'喜剧',poster:'',rating:8.7,director:'周星驰',cast:'周星驰, 张柏芝',runtime:89,overview:'跑龙套演员尹天仇梦想成为真正的演员，在无数次失败中找到了自己表演的尊严与爱情。'},
  {id:99,tmdbId:'tt0146268',title:'大话西游之月光宝盒',enTitle:'A Chinese Odyssey Part One',year:1995,genre:'爱情',poster:'',rating:8.8,director:'刘镇伟',cast:'周星驰, 朱茵',runtime:87,overview:'至尊宝意外穿越回五百年前，遇到紫霞仙子与众妖，开启了那段"一万年"的爱情传奇。'},
  {id:100,tmdbId:'tt0443409',title:'功夫',enTitle:'Kung Fu Hustle',year:2004,genre:'喜剧',poster:'',rating:8.7,director:'周星驰',cast:'周星驰, 元华',runtime:99,overview:'小混混阿星误闯猪笼城寨，发现这里卧虎藏龙，在一场场功夫大战中觉醒了自己的真正力量。'},
  {id:101,tmdbId:'tt2297053',title:'红海行动',enTitle:'Operation Red Sea',year:2018,genre:'动作',poster:'',rating:8.4,director:'林超贤',cast:'张译, 黄景瑜',runtime:138,overview:'中国海军蛟龙突击队在索马里海域展开惊心动魄的撤侨任务，枪林弹雨中绝不放弃任何一个同胞。'},
  {id:102,tmdbId:'tt8613070',title:'少年的你',enTitle:'Better Days',year:2019,genre:'剧情',poster:'',rating:8.6,director:'曾国祥',cast:'周冬雨, 易烊千玺',runtime:135,overview:'高考前夕，被校园欺凌的女生与街头混混相遇，在彼此的保护中找到了穿越黑暗的勇气。'},
  {id:103,tmdbId:'tt0188766',title:'无间道2',enTitle:'Infernal Affairs II',year:2003,genre:'犯罪',poster:'',rating:8.6,director:'刘伟强',cast:'陈冠希, 余文乐, 吴镇宇',runtime:119,overview:'回到1991年，倪氏家族的黑帮权力更迭与警队卧底计划的起源交汇，宿命的齿轮开始转动。'},

  // ─── 日韩经典 (id 104-118) ───
  {id:104,tmdbId:'tt0114746',title:'七宗罪',enTitle:'Oldboy',year:2003,genre:'悬疑',poster:'',rating:8.4,director:'朴赞郁',cast:'崔岷植, 刘智泰',runtime:120,overview:'一个男人被不明身份的人囚禁15年后突然获释，他必须找到绑架者并揭开谜底。'},
  {id:105,tmdbId:'tt0395227',title:'老男孩',enTitle:'Memories of Murder',year:2003,genre:'悬疑',poster:'',rating:8.1,director:'奉俊昊',cast:'宋康昊, 金相庆',runtime:131,overview:'韩国乡村发生连环奸杀案，两名警探以截然不同的方式追查真相，却离凶手越来越远。'},
  {id:106,tmdbId:'tt0758758',title:'入殓师',enTitle:'Departures',year:2008,genre:'剧情',poster:'',rating:8.6,director:'泷田洋二郎',cast:'本木雅弘, 广末凉子',runtime:130,overview:'大提琴手失业后成为入殓师，在生死之间学会了如何与逝者和解，如何珍惜眼前的生活。'},
  {id:107,tmdbId:'tt0245429',title:'千与千寻',enTitle:'Spirited Away',year:2001,genre:'动画',poster:'',rating:9.4,director:'宫崎骏',cast:'柊瑠美, 入野自由',runtime:125,overview:'少女千寻误入神灵世界，为救变成猪的父母在汤屋打工，在奇幻冒险中找回自己的名字与勇气。'},
  {id:108,tmdbId:'tt0097814',title:'魔女宅急便',enTitle:'Kiki\'s Delivery Service',year:1989,genre:'动画',poster:'',rating:8.3,director:'宫崎骏',cast:'高山南, 佐久间玲',runtime:103,overview:'13岁的小魔女琪琪离开家乡独立修行，在海滨城市开设快递服务，在挫折中找到成长的勇气。'},
  {id:109,tmdbId:'tt0046438',title:'东京物语',enTitle:'Tokyo Story',year:1953,genre:'剧情',poster:'',rating:8.7,director:'小津安二郎',cast:'笠智众, 原节子',runtime:136,overview:'年迈的父母从乡下去东京看望儿女，却发现孩子们都忙于自己的生活，只有已故儿子的遗孀真心相待。'},
  {id:110,tmdbId:'tt0087544',title:'天空之城',enTitle:'Castle in the Sky',year:1986,genre:'动画',poster:'',rating:8.4,director:'宫崎骏',cast:'田中真弓, 横泽启子',runtime:124,overview:'少女希达和少年巴鲁一起寻找传说中的浮空城拉普达，飞翔在中世纪的蒸汽与魔法世界。'},
  {id:111,tmdbId:'tt0115963',title:'菊次郎的夏天',enTitle:'Kikujiro',year:1999,genre:'喜剧',poster:'',rating:8.8,director:'北野武',cast:'北野武, 关口雄介',runtime:121,overview:'粗鲁大叔菊次郎陪小男孩正男去寻找从未谋面的母亲，这段荒唐旅程竟成了最好的夏天。'},
  {id:112,tmdbId:'tt4017694',title:'釜山行',enTitle:'Train to Busan',year:2016,genre:'动作',poster:'',rating:8.5,director:'延尚昊',cast:'孔刘, 郑裕美',runtime:118,overview:'一列从首尔开往釜山的列车上爆发丧尸危机，幸存者在密闭空间里为了生存与人性展开搏斗。'},
  {id:113,tmdbId:'tt0364569',title:'母亲',enTitle:'Mother',year:2009,genre:'悬疑',poster:'',rating:8.1,director:'奉俊昊',cast:'金惠子, 元斌',runtime:129,overview:'智障儿子被控谋杀，母亲独自走上寻找真凶的道路，母爱在疯狂的执念中走向危险的边界。'},
  {id:114,tmdbId:'tt0169858',title:'攻壳机动队',enTitle:'Ghost in the Shell',year:1995,genre:'科幻',poster:'',rating:8.0,director:'押井守',cast:'田中敦子, 大冢明夫',runtime:83,overview:'未来世界中，生化人警官草薙素子追踪网络黑客"傀儡师"，探讨了灵魂与电子的终极边界。'},
  {id:115,tmdbId:'tt0050980',title:'野草莓',enTitle:'Wild Strawberries',year:1957,genre:'剧情',poster:'',rating:8.2,director:'英格玛·伯格曼',cast:'维克多·斯约斯特洛姆, 毕比·安德森',runtime:91,overview:'年迈教授驱车前往接受荣誉学位的途中，梦境与现实交织着关于死亡、孤独和和解的冥想。'},
  {id:116,tmdbId:'tt0071129',title:'镜子',enTitle:'Mirror',year:1975,genre:'剧情',poster:'',rating:8.0,director:'安德烈·塔可夫斯基',cast:'玛格丽特·捷列霍娃',runtime:107,overview:'一个弥留之人回忆自己的一生——童年、母亲、战争和俄罗斯大地，诗意与记忆碎片般流淌。'},
  {id:117,tmdbId:'tt0072443',title:'潜行者',enTitle:'Stalker',year:1979,genre:'科幻',poster:'',rating:8.1,director:'安德烈·塔可夫斯基',cast:'亚历山大·凯伊达诺夫斯基',runtime:163,overview:'一名向导带领作家和教授穿越神秘禁区"The Zone"，去寻找能实现最深愿望的房间。'},
  {id:118,tmdbId:'tt0056869',title:'八部半',enTitle:'8½',year:1963,genre:'剧情',poster:'',rating:8.1,director:'费德里科·费里尼',cast:'马塞洛·马斯楚安尼',runtime:138,overview:'陷入创作危机的导演在现实、回忆与幻想中挣扎，所有人的期待把他推向崩溃的边缘。'},

  // ─── 动画 (id 119-132) ───
  {id:119,tmdbId:'tt0398286',title:'魔发奇缘',enTitle:'Tangled',year:2010,genre:'动画',poster:'',rating:8.0,director:'内森·格雷诺',cast:'曼迪·摩尔, 扎克瑞·莱维',runtime:100,overview:'拥有魔法长发的公主从高塔逃出，与通缉犯一起踏上追寻天灯的冒险之旅。'},
  {id:120,tmdbId:'tt0363771',title:'哈尔的移动城堡',enTitle:'Howl\'s Moving Castle',year:2004,genre:'动画',poster:'',rating:8.8,director:'宫崎骏',cast:'倍赏千惠子, 木村拓哉',runtime:119,overview:'少女苏菲被女巫诅咒变成了老婆婆，闯入了魔法师哈尔的移动城堡，一段反战反诅咒的温柔旅程。'},
  {id:121,tmdbId:'tt2294629',title:'冰雪奇缘',enTitle:'Frozen',year:2013,genre:'动画',poster:'',rating:8.0,director:'克里斯·巴克',cast:'克里斯汀·贝尔, 伊迪娜·门泽尔',runtime:102,overview:'艾莎的冰雪魔法意外冻结了整个王国，妹妹安娜踏上危险旅途寻找姐姐，用爱融化一切。'},
  {id:122,tmdbId:'tt2096673',title:'头脑特工队',enTitle:'Inside Out',year:2015,genre:'动画',poster:'',rating:8.7,director:'彼特·道格特',cast:'艾米·波勒, 菲利丝·史密斯',runtime:95,overview:'小女孩莱莉脑中的五种情绪精灵努力帮她适应新城市的生活，揭示了我们情绪的奇妙世界。'},
  {id:123,tmdbId:'tt0266543',title:'海底总动员',enTitle:'Finding Nemo',year:2003,genre:'动画',poster:'',rating:8.3,director:'安德鲁·斯坦顿',cast:'阿尔伯特·布鲁克斯, 艾伦·德杰尼勒斯',runtime:100,overview:'小丑鱼爸爸穿越整个海洋寻找失踪的儿子尼莫，一路上结识了健忘的多莉等朋友。'},
  {id:124,tmdbId:'tt0126029',title:'怪物史莱克',enTitle:'Shrek',year:2001,genre:'动画',poster:'',rating:8.2,director:'安德鲁·亚当森',cast:'麦克·梅尔斯, 艾迪·墨菲',runtime:90,overview:'暴躁食人魔史莱克为了夺回沼泽地，奉命营救被困高塔的菲奥娜公主，却发现她深藏的秘密。'},
  {id:125,tmdbId:'tt0435761',title:'玩具总动员3',enTitle:'Toy Story 3',year:2010,genre:'动画',poster:'',rating:8.5,director:'李·昂克里奇',cast:'汤姆·汉克斯, 蒂姆·艾伦',runtime:103,overview:'安迪长大要去大学了，玩具们阴差阳错被送到日托所，开始了惊险的越狱大冒险。'},
  {id:126,tmdbId:'tt0114709',title:'玩具总动员',enTitle:'Toy Story',year:1995,genre:'动画',poster:'',rating:8.4,director:'约翰·拉塞特',cast:'汤姆·汉克斯, 蒂姆·艾伦',runtime:81,overview:'牛仔胡迪发现自己不再是主人安迪最爱的玩具，新太空人巴斯光年的出现打破了玩具世界的平静。'},
  {id:127,tmdbId:'tt2948356',title:'疯狂动物城',enTitle:'Zootopia',year:2016,genre:'动画',poster:'',rating:9.2,director:'拜伦·霍华德',cast:'金妮弗·古德温, 杰森·贝特曼',runtime:109,overview:'兔子朱迪成为动物城第一位兔子警官，与狐狸尼克联手追查失踪动物案件，挑战偏见与刻板印象。'},
  {id:128,tmdbId:'tt3606756',title:'你的名字',enTitle:'Your Name',year:2016,genre:'动画',poster:'',rating:8.7,director:'新海诚',cast:'神木隆之介, 上白石萌音',runtime:106,overview:'东京男孩和乡下女孩在梦中交换身体，当他们想要见面时，却发现隔着无法跨越的时间与距离。'},
  {id:129,tmdbId:'tt3521164',title:'海洋奇缘',enTitle:'Moana',year:2016,genre:'动画',poster:'',rating:8.1,director:'罗恩·克莱蒙兹',cast:'奥丽伊·卡瓦洛, 道恩·强森',runtime:107,overview:'波利尼西亚少女莫阿娜被大海选中，找到半神毛伊，一起归还特菲提之心，拯救她的岛屿。'},
  {id:130,tmdbId:'tt1049413',title:'飞屋环游记',enTitle:'Up',year:2009,genre:'动画',poster:'',rating:8.5,director:'彼特·道格特',cast:'爱德华·阿斯纳, 乔丹·长井',runtime:96,overview:'老人卡尔用上万个气球让老屋飞上天空，带上小胖子罗素去南美洲完成与亡妻未竟的冒险。'},
  {id:131,tmdbId:'tt0110357',title:'狮子王',enTitle:'The Lion King',year:1994,genre:'动画',poster:'',rating:9.0,director:'罗杰·阿勒斯',cast:'马修·布罗德里克, 杰瑞米·艾恩斯',runtime:88,overview:'小狮子辛巴被叔叔刀疤陷害流亡，在友情与责任的召唤下，回到荣耀王国夺回应有的王位。'},
  {id:132,tmdbId:'tt1950186',title:'超能陆战队',enTitle:'Big Hero 6',year:2014,genre:'动画',poster:'',rating:8.3,director:'唐·霍尔',cast:'瑞安·波特, 斯科特·埃德希特',runtime:102,overview:'天才少年阿宏与充气机器人大白组成超能陆战队，为哥哥的离世寻找真相并守护城市。'},

  // ─── 爱情 (id 133-143) ───
  {id:133,tmdbId:'tt0108160',title:'西雅图夜未眠',enTitle:'Sleepless in Seattle',year:1993,genre:'爱情',poster:'',rating:7.7,director:'诺拉·艾芙隆',cast:'汤姆·汉克斯, 梅格·瑞恩',runtime:105,overview:'失去妻子的男人在电台诉说心声，远在西雅图的电台女主持被深深打动，命运在情人节这天交汇。'},
  {id:134,tmdbId:'tt0108002',title:'英国病人',enTitle:'The English Patient',year:1996,genre:'爱情',poster:'',rating:7.8,director:'安东尼·明格拉',cast:'拉尔夫·费因斯, 克里斯汀·斯科特·托马斯',runtime:162,overview:'二战末期，一起烧伤的无名男子躺在意大利修道院，在回忆中讲述了北非沙漠里一段禁忌的爱情。'},
  {id:135,tmdbId:'tt0093779',title:'末代皇帝',enTitle:'The Last Emperor',year:1987,genre:'剧情',poster:'',rating:9.0,director:'贝纳尔多·贝托鲁奇',cast:'尊龙, 陈冲, 邬君梅',runtime:163,overview:'溥仪从三岁登基到成为伪满洲国傀儡再到普通公民的一生，见证了半个世纪中国历史巨变。'},
  {id:136,tmdbId:'tt0250224',title:'人鬼情未了',enTitle:'Ghost',year:1990,genre:'爱情',poster:'',rating:7.8,director:'杰瑞·扎克',cast:'帕特里克·斯威兹, 黛米·摩尔',runtime:127,overview:'被谋杀的男人灵魂留在人间守护恋人，借助灵媒的帮助完成未竟之事和最后的告别。'},
  {id:137,tmdbId:'tt0064116',title:'罗马假日',enTitle:'Roman Holiday',year:1953,genre:'爱情',poster:'',rating:8.8,director:'威廉·惠勒',cast:'奥黛丽·赫本, 格利高里·派克',runtime:118,overview:'厌倦宫廷生活的公主溜出使馆，与记者在罗马度过了永生难忘的一天自由生活。'},
  {id:138,tmdbId:'tt0116209',title:'英国病人',enTitle:'Notting Hill',year:1999,genre:'爱情',poster:'',rating:7.8,director:'罗杰·米歇尔',cast:'朱莉娅·罗伯茨, 休·格兰特',runtime:124,overview:'好莱坞大明星走进伦敦诺丁山一家小书店，与平凡店主上演了跨越身份与名气的浪漫爱情。'},
  {id:139,tmdbId:'tt0259446',title:'我的野蛮女友',enTitle:'My Sassy Girl',year:2001,genre:'爱情',poster:'',rating:8.3,director:'郭在容',cast:'全智贤, 车太贤',runtime:123,overview:'善良的大学生在地铁上救了一个醉酒的女孩，开始了被"野蛮女友"反复折腾却甜蜜无比的恋爱。'},
  {id:140,tmdbId:'tt0059742',title:'音乐之声',enTitle:'The Sound of Music',year:1965,genre:'爱情',poster:'',rating:8.2,director:'罗伯特·怀斯',cast:'朱莉·安德鲁斯, 克里斯托弗·普卢默',runtime:172,overview:'活泼的修女玛利亚来到海军上校家做家庭教师，用音乐和爱融化了七个孩子和上校的冰冷内心。'},
  {id:141,tmdbId:'tt0094947',title:'剪刀手爱德华',enTitle:'Edward Scissorhands',year:1990,genre:'爱情',poster:'',rating:8.2,director:'蒂姆·波顿',cast:'约翰尼·德普, 薇诺娜·瑞德',runtime:105,overview:'人造人爱德华有着锋利的剪刀手却有着最温柔的心，在郊区小镇里经历了一场美丽而忧伤的爱情。'},
  {id:142,tmdbId:'tt0100405',title:'人鬼情未了',enTitle:'Pretty Woman',year:1990,genre:'爱情',poster:'',rating:7.5,director:'盖瑞·马歇尔',cast:'理查·基尔, 朱莉娅·罗伯茨',runtime:119,overview:'亿万富翁在洛杉矶雇佣了一位街头女郎作为一周社交伴侣，没想到灰姑娘的故事真的发生了。'},
  {id:143,tmdbId:'tt0414993',title:'恋恋笔记本',enTitle:'The Notebook',year:2004,genre:'爱情',poster:'',rating:8.3,director:'尼克·卡萨维茨',cast:'瑞恩·高斯林, 瑞秋·麦克亚当斯',runtime:123,overview:'老人每天为失忆的妻子读一本笔记本里的故事，那个关于他们年轻时不顾一切去相爱的故事。'},

  // ─── 喜剧 (id 144-153) ───
  {id:144,tmdbId:'tt0120484',title:'楚门的世界',enTitle:'The Truman Show',year:1998,genre:'喜剧',poster:'',rating:9.0,director:'彼得·威尔',cast:'金·凯瑞, 劳拉·琳妮',runtime:103,overview:'楚门从出生起就活在全球直播的真人秀里，当他发现真相，毅然踏上寻找真实世界的航程。'},
  {id:145,tmdbId:'tt0211915',title:'天使爱美丽',enTitle:'Amélie',year:2001,genre:'喜剧',poster:'',rating:8.6,director:'让-皮埃尔·热内',cast:'奥黛丽·塔图, 马修·卡索维茨',runtime:122,overview:'巴黎咖啡馆女侍用自己独特的方式默默帮助身边的人，却在面对自己的爱情时畏缩不前。'},
  {id:146,tmdbId:'tt0338013',title:'暖暖内含光',enTitle:'Eternal Sunshine of the Spotless Mind',year:2004,genre:'爱情',poster:'',rating:8.4,director:'米歇尔·贡德里',cast:'金·凯瑞, 凯特·温斯莱特',runtime:108,overview:'分手后两人选择了删除对方记忆的手术，但在记忆被擦除的过程中才发现爱得有多深。'},
  {id:147,tmdbId:'tt0365748',title:'僵尸肖恩',enTitle:'Shaun of the Dead',year:2004,genre:'喜剧',poster:'',rating:8.0,director:'埃德加·赖特',cast:'西蒙·佩吉, 尼克·弗罗斯特',runtime:99,overview:'伦敦爆发僵尸危机，打工人肖恩拖着老妈、前女友和死党去温彻斯特酒吧喝酒避难的爆笑之旅。'},
  {id:148,tmdbId:'tt0091042',title:'春天不是读书天',enTitle:'Ferris Bueller\'s Day Off',year:1986,genre:'喜剧',poster:'',rating:8.0,director:'约翰·休斯',cast:'马修·布罗德里克, 阿兰·卢克',runtime:103,overview:'高中生菲利斯装病逃学一天，带着好朋友和女友在芝加哥的街头尽情享受青春的自由。'},
  {id:149,tmdbId:'tt0071853',title:'巨蟒与圣杯',enTitle:'Monty Python and the Holy Grail',year:1975,genre:'喜剧',poster:'',rating:8.3,director:'特里·吉列姆',cast:'格雷厄姆·查普曼, 约翰·克里斯',runtime:91,overview:'亚瑟王和他的骑士们在英国四处寻找圣杯，一路上遇到了兔子杀手、不死骑士等荒诞至极的挑战。'},
  {id:150,tmdbId:'tt0098635',title:'当哈利遇上莎莉',enTitle:'When Harry Met Sally',year:1989,genre:'爱情',poster:'',rating:8.0,director:'罗伯·莱纳',cast:'比利·克里斯托, 梅格·瑞恩',runtime:96,overview:'哈利和莎莉在十一年里数次偶遇，从彼此讨厌到成为最好的朋友，最终发现真爱就在身边。'},
  {id:151,tmdbId:'tt0079470',title:'万世魔星',enTitle:'Life of Brian',year:1979,genre:'喜剧',poster:'',rating:8.1,director:'特里·琼斯',cast:'格雷厄姆·查普曼, 约翰·克里斯',runtime:94,overview:'在耶稣诞生的同一时期，一个误打误撞被当成救世主的布赖恩，上演了一场荒诞而机智的宗教讽刺。'},
  {id:152,tmdbId:'tt0117951',title:'猜火车',enTitle:'Trainspotting',year:1996,genre:'剧情',poster:'',rating:8.3,director:'丹尼·博伊尔',cast:'伊万·麦克格雷格, 艾文·布莱纳',runtime:93,overview:'爱丁堡一群海洛因瘾君子的挣扎与放纵，"选择生活"的独白背后是堕落与救赎的交锋。'},
  {id:153,tmdbId:'tt0388795',title:'撞车',enTitle:'Crash',year:2004,genre:'剧情',poster:'',rating:7.8,director:'保罗·哈吉斯',cast:'桑德拉·布洛克, 唐·钱德尔',runtime:112,overview:'洛杉矶街头，各色人种碰撞又连接，种族偏见、恐惧和善意在36小时里交织成命运之网。'},

  // ─── 科幻/动作/战争 (id 154-177) ───
  {id:154,tmdbId:'tt0078748',title:'异形',enTitle:'Alien',year:1979,genre:'科幻',poster:'',rating:8.5,director:'雷德利·斯科特',cast:'西格妮·韦弗, 汤姆·斯凯里特',runtime:117,overview:'商业飞船诺斯托罗莫号收到求救信号，带回致命的外星生物，完美生命体的猎杀将船员逐一吞噬。'},
  {id:155,tmdbId:'tt0090605',title:'异形2',enTitle:'Aliens',year:1986,genre:'科幻',poster:'',rating:8.4,director:'詹姆斯·卡梅隆',cast:'西格妮·韦弗, 迈克尔·比恩',runtime:137,overview:'蕾普利回到已经被异形占领的殖民星球，与海军陆战队一起对抗成百上千的异形大军。'},
  {id:156,tmdbId:'tt0083658',title:'银翼杀手',enTitle:'Blade Runner',year:1982,genre:'科幻',poster:'',rating:8.2,director:'雷德利·斯科特',cast:'哈里森·福特, 鲁特格尔·哈尔',runtime:117,overview:'2019年洛杉矶，退休银翼杀手续追捕逃亡的复制人，在与复制人的交锋中质疑了"何为人性"。'},
  {id:157,tmdbId:'tt0070047',title:'驱魔人',enTitle:'The Exorcist',year:1973,genre:'悬疑',poster:'',rating:8.1,director:'威廉·弗莱德金',cast:'艾伦·伯斯汀, 琳达·布莱尔',runtime:122,overview:'小女孩被恶魔附身，两位神父以信仰为武器进行了一场与邪恶力量殊死搏斗的驱魔仪式。'},
  {id:158,tmdbId:'tt0081505',title:'闪灵',enTitle:'The Shining',year:1980,genre:'悬疑',poster:'',rating:8.4,director:'斯坦利·库布里克',cast:'杰克·尼科尔森, 雪莉·杜瓦尔',runtime:146,overview:'作家杰克带全家到偏僻酒店做冬季看管人，酒店里潜藏的灵异力量将他推向了疯狂与暴力。'},
  {id:159,tmdbId:'tt0103064',title:'终结者2：审判日',enTitle:'Terminator 2: Judgment Day',year:1991,genre:'科幻',poster:'',rating:8.6,director:'詹姆斯·卡梅隆',cast:'阿诺·施瓦辛格, 琳达·汉密尔顿',runtime:137,overview:'未来领袖少年约翰与重编程的T-800终结者对抗更先进的液态金属机器人T-1000。'},
  {id:160,tmdbId:'tt0088247',title:'终结者',enTitle:'The Terminator',year:1984,genre:'科幻',poster:'',rating:8.2,director:'詹姆斯·卡梅隆',cast:'阿诺·施瓦辛格, 琳达·汉密尔顿',runtime:107,overview:'来自2029年的赛博格杀手被派往1984年刺杀未来的反抗军领袖之母，未来战士也穿越而来保护她。'},
  {id:161,tmdbId:'tt1201607',title:'哈利·波特与死亡圣器(下)',enTitle:'Harry Potter and the Deathly Hallows Part 2',year:2011,genre:'奇幻',poster:'',rating:8.5,director:'大卫·叶茨',cast:'丹尼尔·雷德克里夫, 艾玛·沃特森',runtime:130,overview:'哈利与伏地魔的最终决战在霍格沃茨打响，正义与邪恶的终极较量决定了魔法世界的命运。'},
  {id:162,tmdbId:'tt0330373',title:'哈利·波特与火焰杯',enTitle:'Harry Potter and the Goblet of Fire',year:2005,genre:'奇幻',poster:'',rating:8.2,director:'迈克·内威尔',cast:'丹尼尔·雷德克里夫, 鲁伯特·格林特',runtime:157,overview:'三强争霸赛在霍格沃茨举办，哈利意外被选为第四名参赛者，同时伏地魔的归来已悄然酝酿。'},
  {id:163,tmdbId:'tt0241527',title:'哈利·波特与魔法石',enTitle:'Harry Potter and the Philosopher\'s Stone',year:2001,genre:'奇幻',poster:'',rating:8.3,director:'克里斯·哥伦布',cast:'丹尼尔·雷德克里夫, 艾玛·沃特森',runtime:152,overview:'11岁的哈利发现自己原来是巫师，被带到霍格沃茨魔法学校，开始了一段改变一生的魔法冒险。'},
  {id:164,tmdbId:'tt0073195',title:'大白鲨',enTitle:'Jaws',year:1975,genre:'悬疑',poster:'',rating:8.1,director:'史蒂文·斯皮尔伯格',cast:'罗伊·施奈德, 罗伯特·肖',runtime:124,overview:'一条巨型大白鲨在小岛海域频繁袭人，警长与海洋生物学家和猎鲨老船长出海捕杀这个深海怪物。'},
  {id:165,tmdbId:'tt0095016',title:'虎胆龙威',enTitle:'Die Hard',year:1988,genre:'动作',poster:'',rating:8.2,director:'约翰·麦克蒂尔南',cast:'布鲁斯·威利斯, 艾伦·瑞克曼',runtime:132,overview:'纽约警探约翰·麦克莱恩在圣诞夜独闯被恐怖分子占领的洛杉矶大楼，赤脚上演了一场孤胆英雄。'},
  {id:166,tmdbId:'tt0468569',title:'蝙蝠侠：黑暗骑士',enTitle:'The Dark Knight',year:2008,genre:'动作',poster:'',rating:9.0,director:'克里斯托弗·诺兰',cast:'克里斯蒂安·贝尔, 希斯·莱杰',runtime:152,overview:'蝙蝠侠与小丑的正面交锋，哥谭市在混乱与秩序之间摇摆，一个关于英雄堕落的黑色寓言。'},
  {id:167,tmdbId:'tt0133093',title:'黑客帝国',enTitle:'The Matrix',year:1999,genre:'科幻',poster:'',rating:9.1,director:'沃卓斯基姐妹',cast:'基努·里维斯, 劳伦斯·菲什伯恩',runtime:136,overview:'程序员尼奥发现现实世界不过是由AI创造的虚拟矩阵，选择吞下红色药丸寻找真相。'},
  {id:168,tmdbId:'tt0234215',title:'黑客帝国2：重装上阵',enTitle:'The Matrix Reloaded',year:2003,genre:'科幻',poster:'',rating:7.2,director:'沃卓斯基姐妹',cast:'基努·里维斯, 劳伦斯·菲什伯恩',runtime:138,overview:'尼奥发现更多关于矩阵的真相，面对史密斯程序的疯狂复制和锡安即将被摧毁的危机。'},
  {id:169,tmdbId:'tt0167404',title:'第六感',enTitle:'The Sixth Sense',year:1999,genre:'悬疑',poster:'',rating:8.2,director:'M·奈特·沙马兰',cast:'布鲁斯·威利斯, 海利·乔·奥斯蒙',runtime:107,overview:'儿童心理学家帮助能看见死者的男孩，却发现了一个颠覆所有认知的真相——"I see dead people"。'},
  {id:170,tmdbId:'tt0066921',title:'发条橙',enTitle:'A Clockwork Orange',year:1971,genre:'犯罪',poster:'',rating:8.3,director:'斯坦利·库布里克',cast:'马尔科姆·麦克道威尔',runtime:136,overview:'少年阿历克斯以暴力为乐，被政府强制接受"厌恶疗法"后，失去了自由意志的他反而成了受害者。'},
  {id:171,tmdbId:'tt0071411',title:'教父2',enTitle:'The Godfather Part II',year:1974,genre:'犯罪',poster:'',rating:9.0,director:'弗朗西斯·科波拉',cast:'阿尔·帕西诺, 罗伯特·德尼罗',runtime:202,overview:'年轻维托在纽约白手起家建立黑帮帝国，中年迈克尔在权力巅峰走向孤独。两代教父的史诗交叠。'},
  {id:172,tmdbId:'tt0477348',title:'无间道风云',enTitle:'The Departed',year:2006,genre:'犯罪',poster:'',rating:8.5,director:'马丁·斯科塞斯',cast:'莱昂纳多·迪卡普里奥, 马特·达蒙',runtime:151,overview:'波士顿警察派卧底打入黑帮，黑帮也派人渗透警队，两头的老鼠都在拼命不被发现。'},
  {id:173,tmdbId:'tt0084787',title:'怪形',enTitle:'The Thing',year:1982,genre:'科幻',poster:'',rating:8.2,director:'约翰·卡朋特',cast:'库尔特·拉塞尔',runtime:109,overview:'南极科考站队员发现了一个能模仿任何生物的异形，在彼此猜忌中上演了冰封大陆上的恐怖生存。'},
  {id:174,tmdbId:'tt0061512',title:'铁窗喋血',enTitle:'Cool Hand Luke',year:1967,genre:'剧情',poster:'',rating:8.1,director:'斯图尔特·罗森博格',cast:'保罗·纽曼, 乔治·肯尼迪',runtime:126,overview:'一个永不屈服的男人在监狱里用微笑和倔强挑战体制。"What we have here is failure to communicate."'},
  {id:175,tmdbId:'tt0047396',title:'后窗',enTitle:'Rear Window',year:1954,genre:'悬疑',poster:'',rating:8.7,director:'阿尔弗雷德·希区柯克',cast:'詹姆斯·斯图尔特, 格蕾丝·凯利',runtime:112,overview:'腿部骨折的摄影师无聊时偷窥邻居，竟目睹了一桩谋杀案，被困在轮椅上的他成了移动的受害者。'},
  {id:176,tmdbId:'tt0052357',title:'迷魂记',enTitle:'Vertigo',year:1958,genre:'悬疑',poster:'',rating:8.3,director:'阿尔弗雷德·希区柯克',cast:'詹姆斯·斯图尔特, 金·诺瓦克',runtime:128,overview:'退休警探受雇跟踪神秘女子，被对她不可遏制的迷恋卷入了一场精心设计的谋杀与幻象之中。'},
  {id:177,tmdbId:'tt0053125',title:'西北偏北',enTitle:'North by Northwest',year:1959,genre:'悬疑',poster:'',rating:8.3,director:'阿尔弗雷德·希区柯克',cast:'加里·格兰特, 爱娃·玛丽·森特',runtime:136,overview:'广告人罗杰被误认为间谍，从纽约到拉什莫尔山被迫上演了一场横跨美国的生死追逐。'},

  // ─── 近年佳作 (id 178-201) ───
  {id:178,tmdbId:'tt2582802',title:'爆裂鼓手',enTitle:'Whiplash',year:2014,genre:'剧情',poster:'',rating:8.7,director:'达米恩·查泽雷',cast:'迈尔斯·特勒, J·K·西蒙斯',runtime:106,overview:'年轻鼓手在魔鬼导师的疯狂压榨下，拼尽全力追求极致爵士乐的完美——血汗和天赋的极限博弈。'},
  {id:179,tmdbId:'tt3783958',title:'爱乐之城',enTitle:'La La Land',year:2016,genre:'爱情',poster:'',rating:8.3,director:'达米恩·查泽雷',cast:'瑞恩·高斯林, 艾玛·斯通',runtime:128,overview:'洛杉矶，渴望成为演员的米娅与爵士钢琴手塞巴斯蒂安相爱，在追梦路上两人必须要做出艰难的选择。'},
  {id:180,tmdbId:'tt5463162',title:'死侍2',enTitle:'Deadpool 2',year:2018,genre:'动作',poster:'',rating:7.8,director:'大卫·雷奇',cast:'瑞安·雷诺兹, 乔什·布洛林',runtime:119,overview:'死侍为保护变种少年拉塞尔组建了X特遣队，嘴炮和战斗双管齐下，打破第四面墙的恶搞永不停歇。'},
  {id:181,tmdbId:'tt5027774',title:'三块广告牌',enTitle:'Three Billboards Outside Ebbing, Missouri',year:2017,genre:'剧情',poster:'',rating:8.7,director:'马丁·麦克唐纳',cast:'弗兰西斯·麦克多蒙德, 山姆·洛克威尔',runtime:115,overview:'女儿被奸杀数月未破案，愤怒的母亲竖起三块广告牌公开质问警长，小镇的怒火与人性就此引爆。'},
  {id:182,tmdbId:'tt4975722',title:'月光男孩',enTitle:'Moonlight',year:2016,genre:'剧情',poster:'',rating:7.9,director:'巴里·詹金斯',cast:'崔凡特·罗兹, 安德烈·霍兰德',runtime:111,overview:'一个黑人男孩在迈阿密的成长三部曲：童年被欺凌、少年发现性取向、成年后与过去的自我和解。'},
  {id:183,tmdbId:'tt1895587',title:'聚焦',enTitle:'Spotlight',year:2015,genre:'剧情',poster:'',rating:8.3,director:'汤姆·麦卡锡',cast:'马克·鲁弗洛, 迈克尔·基顿',runtime:129,overview:'波士顿环球报的调查报道小组揭露了天主教会内部性侵儿童的系统性丑闻，揭开了一场全球性风暴。'},
  {id:184,tmdbId:'tt2119532',title:'血战钢锯岭',enTitle:'Hacksaw Ridge',year:2016,genre:'战争',poster:'',rating:8.6,director:'梅尔·吉布森',cast:'安德鲁·加菲尔德, 萨姆·沃辛顿',runtime:139,overview:'二战中，不愿持枪的医务兵戴斯蒙德·道斯在钢锯岭战场上独自救下了75名战友的生命。'},
  {id:185,tmdbId:'tt9362722',title:'花月杀手',enTitle:'Killers of the Flower Moon',year:2023,genre:'犯罪',poster:'',rating:8.0,director:'马丁·斯科塞斯',cast:'莱昂纳多·迪卡普里奥, 罗伯特·德尼罗',runtime:206,overview:'1920年代奥色治族人因石油暴富，一系列谋杀案接连发生，FBI的早期调查揭开了巨大的阴谋。'},
  {id:186,tmdbId:'tt6710474',title:'瞬息全宇宙',enTitle:'Everything Everywhere All at Once',year:2022,genre:'科幻',poster:'',rating:8.6,director:'关家永',cast:'杨紫琼, 关继威',runtime:139,overview:'华裔洗衣店老板娘伊芙琳穿越平行宇宙，在千奇百怪的自己中发现爱与和解才是拯救一切的力量。'},
  {id:187,tmdbId:'tt1745960',title:'壮志凌云：独行侠',enTitle:'Top Gun: Maverick',year:2022,genre:'动作',poster:'',rating:8.4,director:'约瑟夫·科辛斯基',cast:'汤姆·克鲁斯, 迈尔斯·特勒',runtime:131,overview:'服役30年的马弗里克不愿晋升也不肯退隐，被召回训练新一代飞行员执行一项几乎不可能完成的任务。'},
  {id:188,tmdbId:'tt7286456',title:'小丑',enTitle:'Joker',year:2019,genre:'犯罪',poster:'',rating:8.6,director:'托德·菲利普斯',cast:'华金·菲尼克斯, 罗伯特·德尼罗',runtime:122,overview:'失意的脱口秀演员亚瑟·弗莱克在哥谭市的冷漠中一点点崩溃，最终化身小丑，引爆整个城市的疯狂。'},
  {id:189,tmdbId:'tt7784604',title:'遗传厄运',enTitle:'Hereditary',year:2018,genre:'悬疑',poster:'',rating:7.6,director:'阿里·艾斯特',cast:'托妮·科莱特, 亚历克斯·沃尔夫',runtime:127,overview:'外婆去世后，一个家庭的秘密阴影逐渐浮现，细思极恐的超自然力量将每个人拖入万劫不复。'},
  {id:190,tmdbId:'tt1160419',title:'沙丘',enTitle:'Dune',year:2021,genre:'科幻',poster:'',rating:8.1,director:'丹尼斯·维伦纽瓦',cast:'提莫西·查拉梅, 丽贝卡·弗格森',runtime:155,overview:'天才少年保罗来到全宇宙最危险的沙漠星球，卷入了争夺香料和帝国霸权的星际漩涡。'},
  {id:191,tmdbId:'tt0166924',title:'穆赫兰道',enTitle:'Mulholland Drive',year:2001,genre:'悬疑',poster:'',rating:8.0,director:'大卫·林奇',cast:'娜奥米·沃茨, 劳拉·哈灵',runtime:147,overview:'一名失忆女子与来到好莱坞追梦的演员之间发生了一段如梦似幻、层层嵌套的身份谜团。'},
  {id:192,tmdbId:'tt0169547',title:'美国心玫瑰情',enTitle:'American Beauty',year:1999,genre:'剧情',poster:'',rating:8.5,director:'萨姆·门德斯',cast:'凯文·史派西, 安妮特·贝宁',runtime:122,overview:'中年危机中的男人开始重新审视生活，在女儿的同学身上找到青春的回眸，在玫瑰花瓣里寻找美。'},
  {id:193,tmdbId:'tt0120815',title:'拯救大兵瑞恩',enTitle:'Saving Private Ryan',year:1998,genre:'战争',poster:'',rating:8.9,director:'史蒂文·斯皮尔伯格',cast:'汤姆·汉克斯, 马特·达蒙',runtime:169,overview:'诺曼底登陆后，一支八人小队深入敌后寻找唯一幸存的瑞恩家小儿子，战争的残酷与人性尽在其中。'},
  {id:194,tmdbId:'tt0069293',title:'索拉里斯',enTitle:'Solaris',year:1972,genre:'科幻',poster:'',rating:8.0,director:'安德烈·塔可夫斯基',cast:'多纳塔斯·巴尼奥尼斯',runtime:167,overview:'心理学家被派往绕行索拉里斯星的空间站，发现这个神秘海洋星球能让最深处的记忆化为肉身。'},
  {id:195,tmdbId:'tt0057565',title:'天国与地狱',enTitle:'High and Low',year:1963,genre:'悬疑',poster:'',rating:8.4,director:'黑泽明',cast:'三船敏郎, 仲代达矢',runtime:143,overview:'鞋业巨头面临其司机的儿子被绑架的危机，在赎金与商业之间痛苦抉择，警方的追捕步步深入。'},
  {id:196,tmdbId:'tt0083929',title:'芬妮与亚历山大',enTitle:'Fanny and Alexander',year:1982,genre:'剧情',poster:'',rating:8.5,director:'英格玛·伯格曼',cast:'贝蒂尔·古韦, 佩妮拉·奥温',runtime:188,overview:'20世纪初瑞典，兄妹两人在父亲去世后被冷酷继父虐待，最终在犹太商人家中找到魔法与温暖。'},
  {id:197,tmdbId:'tt0012349',title:'寻子遇仙记',enTitle:'The Kid',year:1921,genre:'喜剧',poster:'',rating:8.3,director:'查理·卓别林',cast:'查理·卓别林, 杰基·库根',runtime:68,overview:'流浪汉在垃圾箱旁捡到一个弃婴，用尽一生温柔将这个孩子抚养长大，笑与泪交织的无声经典。'},
  {id:198,tmdbId:'tt0027977',title:'摩登时代',enTitle:'Modern Times',year:1936,genre:'喜剧',poster:'',rating:8.7,director:'查理·卓别林',cast:'查理·卓别林, 宝莲·高黛',runtime:87,overview:'卓别林的流浪汉在大萧条时代的工业化机器中挣扎求生，荒诞幽默中是对机械化时代的深刻批判。'},
  {id:199,tmdbId:'tt0021749',title:'城市之光',enTitle:'City Lights',year:1931,genre:'爱情',poster:'',rating:8.7,director:'查理·卓别林',cast:'查理·卓别林, 弗吉尼亚·切瑞尔',runtime:87,overview:'流浪汉爱上了盲人卖花女，为了她不惜一切代价赚钱做手术，一段无声电影时代最动人的爱情故事。'},
  {id:200,tmdbId:'tt0032553',title:'大独裁者',enTitle:'The Great Dictator',year:1940,genre:'喜剧',poster:'',rating:8.5,director:'查理·卓别林',cast:'查理·卓别林, 宝莲·高黛',runtime:125,overview:'一位犹太理发师与大独裁者长得一模一样，两人被调换后，理发师发表了那篇载入史册的和平演讲。'},
  {id:201,tmdbId:'tt0043014',title:'日落大道',enTitle:'Sunset Boulevard',year:1950,genre:'剧情',poster:'',rating:8.6,director:'比利·怀尔德',cast:'威廉·霍尔登, 格洛丽亚·斯旺森',runtime:110,overview:'落魄编剧躲进昔日默片女星的豪宅，被她病态的占有欲和重返聚光灯的执念一步步吞噬。'}
];
